katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import delete_task, login_user
from todolist.views import logout_user
from todolist.views import register
from todolist.views import show_todolist
from todolist.views import create_task
from todolist.views import delete_task
from todolist.views import update_task
from todolist.views import show_json
from todolist.views import todolist_add
from todolist.views import todolist_delete
app_name='todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('delete_task/<str:task_id>/', delete_task, name="delete_task"),
    path('update_task/<str:task_id>/', update_task, name="update_task"),
    path('json/', show_json, name='show_json'),
    path('add/', todolist_add, name='todolist_add'),
    path('delete/<str:task_id>/', todolist_delete, name='todolist_delete'),
]

todolist/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth import settings

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields=['title', 'description']

class UpdateForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = ['title', 'description', 'is_finished']

todolist/views.py
from ast import Delete
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import Task
from todolist.forms import TaskForm
from todolist.forms import UpdateForm
import json
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt



# Create your views here.
@login_required(login_url='/wishlist/login/')
@csrf_exempt
def todolist_delete(request, task_id):
    if request.method == "POST":
        data = get_object_or_404(Task, pk=task_id, user=request.user)
        data.delete()
        
    return HttpResponse()

@login_required(login_url='/wishlist/login/')
def todolist_add(request):
    if request.method == "POST":
        data = json.loads(request.POST['data'])

        new_task = Task(title=data["title"], description=data["description"], user=request.user)
        new_task.save()

        return HttpResponse(serializers.serialize("json", [new_task]), content_type="application/json")

    return HttpResponse()


@login_required(login_url='/todolist/login/')
def show_json(request):
    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", tasks), content_type="application/json")

@login_required(login_url='/todolist/login/')
def update_task(request, task_id):
	queryset = Task.objects.get(id=task_id)
	form = UpdateForm(instance=queryset)
	if request.method == 'POST':
		form = UpdateForm(request.POST, instance=queryset)
		if form.is_valid():
			form.save()
			return redirect('todolist:show_todolist')

	context = {
		'form':form
		}

	return render(request, 'update_task.html', context)

@login_required(login_url='/todolist/login/')
def delete_task(request,task_id):
    queryset = Task.objects.get(id=task_id)
    if request.method == 'POST':
        queryset.delete()
        return redirect('todolist:show_todolist')
    
    context = {
        'task':queryset
    }
    return render(request, 'delete_task.html', context)



@login_required(login_url='/todolist/login/')
def show_todolist(request):
    tasks = Task.objects.filter(user=request.user)
    context = {
        'username': request.COOKIES['username'],
        'last_login': request.COOKIES['last_login'],
        'tasks': tasks,
    }
    return render(request, "todolist.html", context)


@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            todolist = form.save(commit=False)
            todolist.user = request.user
            todolist.save()
            return redirect('todolist:show_todolist')

    
    form = TaskForm()

    context = {"forms": form,}

    return render(request, 'create_task.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form, 'user':request.user}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('username', username)
            now = datetime.datetime.now()
            response.set_cookie('last_login', now.strftime("%b. %d, %Y %H:%M:%S")) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return redirect('todolist:login')

todolist/templates/create_task.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <title>Create New Task</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/create_task.css' %}">
    {% endblock meta %}
</head>


<body>
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.serializejson.min.js' %}"></script>


    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <h5 class="navbar-brand">Create New Task</h5>

            <div class="nav navbar-nav navbar-right">
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:show_todolist' %}">Back</a></button>
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:logout' %}">Logout</a></button>
            </div>
        </div>
    </nav>

    <br>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="d-flex align-items-center justify-content-center">
            <div class="d-flex flex-column">
                <div class="d-flex flex-row">
                    <input type="text" name="title" placeholder="Task Title" class="form-control">
                </div>
                <div class="d-flex flex-row">
                    <input type="text" name="description" placeholder="Task Description" class="form-control">
                </div>
                <div class="d-flex flex-row align-items-center">
                    <input class="btn login_btn btn-xl btn-primary" type="submit" value="Tambah Task Baru">
                </div>
            </div>
        </div>
    </form>

    <!-- Button trigger modal
    <button type="button" class="btn btn-primary" data-mdb-toggle="modal" data-mdb-target="#exampleModal">
        Launch demo modal
    </button>
    
    Modal
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">...</div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        </div>
    </div> -->


  

    {% endblock content %}
</body>

todolist/templates/delete_task.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	{% block meta %}
	<title>Delete Task</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/todolist.css' %}">
	{% endblock meta %}
</head>

<body>
	{% block content %}

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <h5 class="navbar-brand">Delete Task</h5>

            <div class="nav navbar-nav navbar-right">
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:show_todolist' %}">Back</a></button>
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:logout' %}">Logout</a></button>
            </div>
        </div>
    </nav>
    <br>
    
    <h5 style="text-align:center;">Delete the following task?</h5>
    <div class="row row-cols-1 row-cols-md-4 g-4 justify-content-center">
        <div class="col">
            <div class="card">
                {% if task.is_finished %}
                <div class="card-header text-bg-success text-center">Completed</div>
                {% else %}
                <div class="card-header text-bg-warning text-center">Not Yet Completed</div>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{task.title}}</h5>
                    <p class="card-text">{{task.description}}</p>

                </div>
                <div class="card-footer">
                        <small class="text-muted text-center">Created {{task.date}} by {{task.user}}</small>
                                 
                </div>
            </div>
        </div>
        
    </div>


    <div class="container">
        <div class="vertical-center" style="text-align: center;margin-top: 10px;">
            <form method="POST" action="" class="justify-content-center">
                {% csrf_token %}
                <input class="btn btn-sm btn-danger" type="submit" value="Delete" name="Yes">
            </form>
        </div>
      </div>

    {% endblock content %}
</body>

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
{% block meta %}
<title>Login</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
{% endblock meta %}
</head>

<body>
    {% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        <div class="section">
            <div class="container">
                <div class="row full-height justify-content-center">
                    <div class="col-12 text-center align-self-center py-5">
                        <div class="section pb-5 pt-5 pt-sm-2 text-center">
                            <div class="card-3d-wrap mx-auto">
                                <div class="card-3d-wrapper">
                                    <div class="card-front">
                                        <div class="center-wrap">
                                            <div class="section text-center">
                                                    <h4 class="mb-4 pb-3">Login</h4>
                                                <div class="form-group">
                                                    <input type="text" name="username" placeholder="Your Username" class="form-style" autocomplete="off" autocapitalize="none" autofocus="" required="">
                                                    <i class="input-icon bi bi-person-fill"></i>
                                                </div>	
                                                <div class="form-group mt-2">
                                                    <input type="password" name="password" placeholder="Your Password" class="form-style" autocomplete="off" autocapitalize="none">
                                                    <i class="input-icon bi bi-lock-fill"></i>
                                                </div>
                                                <input class="btn login_btn mt-4" type="submit" value="Submit">
                                                
                                                {% if messages %}
                                                    <ul>
                                                        {% for message in messages %}
                                                            <li class="mb-0 mt-4 text-center">{{ message }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %} 

                                                <p class="mb-0 mt-4 text-center">Belum punya akun? <a href="{% url 'todolist:register' %}" class="link">Buat Akun</a></p>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% endblock content %}
</body>

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <title>Todolist</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/todolist.css' %}">
    {% endblock meta %}
</head>

<body>
    {% block content %}
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid mr">
            <div class="wrapper">
                <h5 class="navbar-brand user">Welcome back, {{username}}!</h5>
                <h5 class="navbar-brand login">Last Login on {{last_login}}</h5>
            </div>
            <div class="nav navbar-nav navbar-right">
                <!-- <button type="button" id="modal-button" class="btn btn-light"><a
                        href="{% url 'todolist:create-task' %}">Create Task</a></button> -->

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Create Task
                </button>
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:logout' %}">Logout</a></button>
            </div>
        </div>
    </nav>

    <br>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.serializejson.min.js' %}"></script>





    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Create Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="" id="createTask">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="title" placeholder="Task Title" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input type="text" name="description" placeholder="Task Description" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input class="btn login_btn btn-xl btn-primary" type="submit" value="Create Task">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        console.log("a")

        var container = document.createElement("div");
        container.classList.add("row", "row-cols-1", "row-cols-md-4", "g-4");

        function getTask() {
            container.innerHTML = "";
            $.get("{% url 'todolist:show_json' %}", function (data) {
                
                $.each(data, function (i, value) {
                    // iterate per task

                    var field = value.fields;
                    console.log("yez",value);

                    var col = document.createElement("div");
                    col.classList.add("col");

                    var card = document.createElement("div");
                    card.classList.add("card");
                    col.appendChild(card);

                    var header = document.createElement("div");
                    if (field.is_finished == true) {
                        header.classList.add("card-header", "text-bg-success", "text-center");
                        header.innerHTML = "Completed";
                    } else {
                        header.classList.add("card-header", "text-bg-warning", "text-center")
                        header.innerHTML = "Not Yet Completed";
                    }

                    var body = document.createElement("div");
                    body.classList.add("card-body");
                    var title = document.createElement("h5");
                    title.classList.add("card-title");
                    title.innerHTML = field.title;
                    var desc = document.createElement("p");
                    desc.classList.add("card-text");
                    desc.innerHTML = field.description;

                    body.appendChild(title);
                    body.appendChild(desc);

                    var footer = document.createElement("div");
                    footer.classList.add("card-footer");

                    card.appendChild(header);
                    card.appendChild(body);
                    card.appendChild(footer);

                    var date = document.createElement("small");
                    date.classList.add("text-muted", "text-center");
                    date.innerHTML = `Created ${field.date}`;

                    var updateBtn = document.createElement("a");
                    updateBtn.classList.add("btn", "btn-primary", "btn-sm", "text-end");
                    updateBtn.innerHTML = "Update";
                    updateBtn.href = "/todolist/update_task/" + value.pk + "/";

                    var deleteBtn = document.createElement("a");
                    deleteBtn.classList.add("btn", "btn-danger", "btn-sm", "text-end");
                    deleteBtn.innerHTML = "Delete";
                    deleteBtn.setAttribute('onclick', `deleteTask(${value.pk})`);

                    footer.appendChild(date);
                    footer.appendChild(deleteBtn);
                    footer.appendChild(updateBtn);

                    container.appendChild(col);
                })

                document.body.appendChild(container)

            })
        }

        function deleteTask(pk) {
            var url = `/todolist/delete/${pk}/`;
            $.ajax({
                url: `/todolist/delete/${pk}/`,
                type: "POST",
                data: {},
                success: function (result) {
                    getTask();
                },

                error: function (xhr, resp, text) {
                        console.log("ada error cuy")
                        console.log("url",url)
                        console.log("xhr", xhr)
                        console.log("resp", resp)
                        console.log("text", text)
                }
            });
        }

        $(document).ready(function () {

            // GET
            getTask()

            // POST
            console.log("cretask")
            $("#createTask").submit(function (e) {
                e.preventDefault();
                console.log("oi oi oi")
                var actionurl = e.currentTarget;
                var formJSON = JSON.stringify($("#createTask").serializeJSON());
                console.log("e", e)
                console.log("json", formJSON)
                console.log("actionurl", actionurl)

                $.ajax({
                    type: "POST",
                    url: "{% url 'todolist:todolist_add' %}",
                    data: {
                        data: formJSON,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },

                    success: function (response) {
                        $(response).each(function (i, value) {
                            
                        });
                        $('#createTask').each(function () {
                            this.reset();
                        });
                        console.log("mantap sukses");
                        getTask();

                        $('#exampleModal').modal('toggle');
                    },

                    error: function (xhr, resp, text) {
                        console.log("ada error")
                        console.log("xhr", xhr)
                        console.log("resp", resp)
                        console.log("text", text)
                    }
                });

            });

        });



    </script>


    <!-- <div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="addTaskForm">
                    {% csrf_token %}
                    <div class="modal-body">
                        <fieldset>
                            <input class="form-control mb-3" type="text" placeholder="Task Title" name="title">
                            <textarea class="form-control mb-3" rows="3" placeholder="Description"
                                name="description"></textarea>
                        </fieldset>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary btnClick">Submit</button>
                    </div>
                </form>
    
            </div>
        </div>
    </div> -->




    <!-- <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for task in tasks %}
        <div class="col">
            <div class="card">
                {% if task.is_finished %}
                <div class="card-header text-bg-success text-center">Completed</div>
                {% else %}
                <div class="card-header text-bg-warning text-center">Not Yet Completed</div>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{task.title}}</h5>
                    <p class="card-text">{{task.description}}</p>

                </div>
                <div class="card-footer">
                        <small class="text-muted text-center">Created {{task.date}} by {{task.user}}</small>
                        <a class="btn btn-sm btn-danger text-end" href="{% url 'todolist:delete_task' task.id %}">Delete</a>
                        <a class="btn btn-sm btn-primary text-end" href="{% url 'todolist:update_task' task.id %}">Update</a>
                        
                </div>
            </div>
        </div>
    {% endfor %}
    </div> -->



    {% endblock content %}

</body>
</html>

todolist/templates/update_task.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	{% block meta %}
	<title>Update Task</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/create_task.css' %}">
	{% endblock meta %}
</head>

<body>
	{% block content %}
	<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <h5 class="navbar-brand">Update Task</h5>

            <div class="nav navbar-nav navbar-right">
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:show_todolist' %}">Back</a></button>
                <button type="button" class="btn btn-light"><a href="{% url 'todolist:logout' %}">Logout</a></button>
            </div>
        </div>
    </nav>
	
	<br>

	<div class="d-flex align-items-center justify-content-center">
		<form method="POST" action="">
			{% csrf_token %}
			{{form}}
			<input class="btn btn-primary" type="submit" value="Update" name="Update">
		</form>
	</div>
	{% endblock content %}
</body>